### ISSUE TITLE
a JSON decode error

### ISSUE THREAD

**Issue by vilhu-github** [mmshivesh/PySnooNotes#1]
Heya, I wanted to let you know about this:

```
['x']
{'NoteTypeID': x, 'SubName': 'x', 'Message': 'x', 'AppliesToUsername': 'x', 'Url': 'x'}
Traceback (most recent call last):
  File "C:\Users\x\Desktop\reddit-bot\x\bot.py", line 101, in <module>
    add_decay(author, subid)
  File "C:\Users\x\Desktop\reddit-bot\x\bot.py", line 87, in add_decay
    sn.add_note_for_user(author, 2310, "x", f"[{amoun}] x", f"x{subid}")
  File "C:\Users\x\Desktop\reddit-bot\x\pysnoonotes\core.py", line 61, in add_note_for_user
    self._authed_request("POST", "/api/note", data={
  File "C:\Users\x\Desktop\reddit-bot\x\pysnoonotes\core.py", line 48, in _authed_request
    return r.json()
  File "C:\Users\x\AppData\Local\Programs\Python\Python38-32\lib\site-packages\requests\models.py", line 898, in json
    return complexjson.loads(self.text, **kwargs)
  File "C:\Users\x\AppData\Local\Programs\Python\Python38-32\lib\json\__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "C:\Users\x\AppData\Local\Programs\Python\Python38-32\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\x\AppData\Local\Programs\Python\Python38-32\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
[Finished in 77.891s]
```
I added a print(data) below line 38 in core.py to get some context for this. The first line in my copypaste is my request for a user's snoonotes (their username), and below that is my request to POST a new note. I've substituted a lot of info with x, sorry about that.

[It posts the note just fine though.](https://i.imgur.com/E3cffHL.png)

I added a 

```
            try:
                return r.json()
            except Exception as e:
                print(e)
```
below the ``if r.ok:``, and it now just occasionally prints ``Expecting value: line 1 column 1 (char 0)``.

Thanks for writing this, it's been great so far!

**Comment by mmshivesh** [comment]
Whoa, thanks for catching that. I’ll add a fix in about a day. 

I didn’t test the note adding feature yet, save for initial tests in an REST client so, thanks!

I was too engrossed trying to implement note removal and setting up for publishing to pypi.

**Comment by mmshivesh** [comment]
I looked into this and it was a stupid bug. When performing a post request, the response is an empty string and consequently, `r.json()` is invalid.

I added a new error type for failed requests `RequestFailedError` and return nothing for POST requests.

Hopefully this fixes everything.

**Comment by mmshivesh** [comment]
@vilhu-github All bugs have been fixed. You can get the latest release from [pypi](https://pypi.org/project/pysnoonotes/). I've also gone ahead and added note deletion support, along with some `pytests`.

**Comment by vilhu-github** [comment]
Ah, you're a legend. Seems to be working perfectly!
